kind: Service
apiVersion: v1
metadata:
  name: pksdemo
spec:
  selector:
    app: pksdemo
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 52.155.169.189
