apiVersion: apps/v1
kind: Deployment
metadata:
  name: pksdemo
spec:
  selector:
      matchLabels:
        app: pksdemo
        tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: pksdemo
        tier: backend
    spec:
      containers:
        - name: pksdemo
          image: nlxarosa/pksdemo:file-test
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/mnt/azure"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile

