apiVersion: apps/v1
kind: Deployment
metadata:
  name: pksdemo
spec:
  selector:
      matchLabels:
        app: pksdemo
        tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: pksdemo
        tier: backend
    spec:
      containers:
        - name: pksdemo
          image: nlxarosa/pksdemo:latest
          ports:
            - containerPort: 8080